import { useState } from "react"
import { LayoutDashboard, Target, Dumbbell, Wallet, BookOpen, FolderGit2, Plus, Check, ChevronRight, HardDrive } from "lucide-react"
import "./App.css"

type Task={id:number;title:string;meta:string;done:boolean}
const start:Task[]=[{id:1,title:"完成 Personal OS 仪表盘 MVP",meta:"工作 · 09:30",done:false},{id:2,title:"力量训练：推（45 分钟）",meta:"健康 · 18:30",done:false},{id:3,title:"学习 React 架构设计 45 分钟",meta:"学习 · 20:30",done:false}]
const menu=[[LayoutDashboard,"概览"],[Target,"计划"],[Dumbbell,"健康"],[Wallet,"财务"],[BookOpen,"学习"],[FolderGit2,"工作台"]] as const
export default function App(){const[tasks,setTasks]=useState(start);const[active,setActive]=useState("概览");const[mobile,setMobile]=useState(false);const done=tasks.filter(t=>t.done).length;const toggle=(id:number)=>setTasks(v=>v.map(t=>t.id===id?{...t,done:!t.done}:t));return <main className="app"><aside className={mobile?"open":""}><div className="brand"><b>P</b><strong>Personal OS</strong></div><nav aria-label="主菜单">{menu.map(([Icon,name])=><button key={name} onClick={()=>{setActive(name);setMobile(false)}} className={active===name?"active":""}><Icon size={18}/><span>{name}</span></button>)}</nav><small><i/>本地数据已同步</small></aside><section className="content"><header><button className="hamburger" onClick={()=>setMobile(!mobile)} aria-label="打开菜单">☰</button><div><label>星期五 · 2026 年 9 月 11 日</label><h1>{active==="概览"?"早上好，xqx。":active}</h1></div><button className="add" onClick={()=>setTasks(v=>[...v,{id:Date.now(),title:"新建待办事项",meta:"工作 · 今天",done:false}])}><Plus size={16}/>快速记录</button></header><section className="focus"><div><label>今日焦点</label><h2>把精力留给真正重要的三件事。</h2><p>今天还有 {tasks.length-done} 项重点待完成；先专注当前任务。</p></div><div className="score"><b>{done}/{tasks.length}</b><span>已完成</span></div></section><div className="heading"><div><label>TODAY</label><h2>今日行动</h2></div><button>查看日程 <ChevronRight size={16}/></button></div><div className="tasks">{tasks.map((t,i)=><article key={t.id} className={t.done?"done":""}><button className="check" onClick={()=>toggle(t.id)} aria-label={"完成 "+t.title}>{t.done&&<Check size={14}/>}</button><em>0{i+1}</em><div><h3>{t.title}</h3><p>{t.meta}</p></div><ChevronRight size={18}/></article>)}</div><div className="heading pulse"><div><label>LIFE PULSE</label><h2>生活脉搏</h2></div></div><div className="cards"><Card icon={<Dumbbell/>} name="健康" title="今晚训练：推" text="本周 2 / 4 次"/><Card icon={<Wallet/>} name="财务" title="¥36" text="今日支出 · 预算剩余 64%"/><Card icon={<BookOpen/>} name="学习" title="12.5 小时" text="本周学习 · 连续 6 天"/><Card icon={<HardDrive/>} name="电脑" title="状态良好" text="可用空间 184 GB"/></div></section></main>}
function Card({icon,name,title,text}:{icon:React.ReactNode;name:string;title:string;text:string}){return <article className="card"><i>{icon}</i><label>{name}</label><h3>{title}</h3><p>{text}</p></article>}
